src/main/java/com/drinkeg/drinkeg/controller/MemberController.java, src/main/java/com/drinkeg/drinkeg/controller/OAuth2Controller.java, src/main/java/com/drinkeg/drinkeg/controller/TokenController.java, src/main/java/com/drinkeg/drinkeg/converter/MemberConverter.java, src/main/java/com/drinkeg/drinkeg/service/loginService/AppleLoginService.java
1. MemberController 에서 tokenService 삭제 -> TokenController 생성
2. MemberController 에서 appleLoginService 삭제 -> OAuth2Controller 생성
3. appleLoginService 가독성 있게 변환
4. MemberConverter 생성
=> #89 Refactor: AppleLogin Refactoring

src/main/java/com/drinkeg/drinkeg/repository/WineRepository.java, src/main/java/com/drinkeg/drinkeg/service/wineService/WineServiceImpl.java
- 기존 공백으로 나누어 검색하는 로직 삭제
- 완전 일치 검색 로직 삭제
- LIKE %검색어% 검색으로만 반환하는 것으로 변경
=> #92 Refactor: 와인 검색 로직 단순화

src/main/java/com/drinkeg/drinkeg/converter/TastingNoteConverter.java, src/main/java/com/drinkeg/drinkeg/domain/TastingNote.java, src/main/java/com/drinkeg/drinkeg/dto/TastingNoteDTO/request/NoteRequestDTO.java, src/main/java/com/drinkeg/drinkeg/dto/TastingNoteDTO/request/NoteUpdateRequestDTO.java, src/main/java/com/drinkeg/drinkeg/dto/TastingNoteDTO/response/NoteResponseDTO.java, src/main/java/com/drinkeg/drinkeg/repository/WineRepository.java, src/main/java/com/drinkeg/drinkeg/service/memberService/MemberService.java, src/main/java/com/drinkeg/drinkeg/service/memberService/MemberServiceImpl.java, src/main/java/com/drinkeg/drinkeg/service/tastingNoteService/TastingNoteServiceImpl.java
- TastingNote 도메인에 시음날짜 (LocalDate tasteDate) 추가
- TastingNote 관련 Service, DTO, Converter에 반영 완료
=> #106 Refactor: TastingNote에 시음 날짜 추가

src/main/java/com/drinkeg/drinkeg/apipayLoad/code/status/ErrorStatus.java, src/main/java/com/drinkeg/drinkeg/converter/MemberConverter.java, src/main/java/com/drinkeg/drinkeg/dto/loginDTO/jwtDTO/JoinDTO.java, src/main/java/com/drinkeg/drinkeg/service/loginService/AppleLoginService.java, src/main/java/com/drinkeg/drinkeg/service/loginService/JoinService.java
- joinService에서 toMember(converter)사용함
- 재입력한 비밀번호 검증 로직 추가
- 비밀번호 유효성 검증 추가
=> ♻️ #89 Refactor: 자체 로그인 부분 검증 로직 추가

src/main/java/com/drinkeg/drinkeg/apipayLoad/code/status/ErrorStatus.java, src/main/java/com/drinkeg/drinkeg/config/SecurityConfig.java, src/main/java/com/drinkeg/drinkeg/config/SwaggerConfig.java, src/main/java/com/drinkeg/drinkeg/controller/MemberController.java, src/main/java/com/drinkeg/drinkeg/controller/OAuth2Controller.java, src/main/java/com/drinkeg/drinkeg/controller/TokenController.java, src/main/java/com/drinkeg/drinkeg/converter/MemberConverter.java, src/main/java/com/drinkeg/drinkeg/jwt/CustomAccessDeniedHandler.java, src/main/java/com/drinkeg/drinkeg/jwt/CustomLogoutFilter.java, src/main/java/com/drinkeg/drinkeg/service/loginService/CustomOAuth2UserService.java, src/main/java/com/drinkeg/drinkeg/service/loginService/CustomUserDetailsService.java, src/main/java/com/drinkeg/drinkeg/service/loginService/JoinService.java
- CustomAuthenticationEntryPoint, CustomAccessDeniedHandler 정상 작동 확인
- 서비스단에서 Converter 사용하도록 변경 (바꾸기 애매한 builder 몇 개 남아이씀)
- 시큐리티 필터 엔드포인트 스웨거 명시
- /login 엔드포인트는 springdoc: show-login-endpoint: true 설정 추가하여 명시(tag, description 등 스웨거 관련 추가 설정 적용이 안되는 문제 개선 필요)
=> #90 Refactor: 스프링 시큐리티 관련 서비스 로직 및 예외처리 리팩토링

src/main/java/com/drinkeg/drinkeg/apipayLoad/code/status/ErrorStatus.java, src/main/java/com/drinkeg/drinkeg/controller/PartyController.java, src/main/java/com/drinkeg/drinkeg/service/partyService/PartyService.java, src/main/java/com/drinkeg/drinkeg/service/partyService/PartyServiceImpl.java
- 모임, 댓글, 대댓글, 모임참여멤버 각각 Refactor해서 전체를 다 받아야 오류 없음
=> #91 Refactor: 모임 Refactor

src/main/java/com/drinkeg/drinkeg/apipayLoad/code/status/ErrorStatus.java, src/main/java/com/drinkeg/drinkeg/controller/CommentController.java, src/main/java/com/drinkeg/drinkeg/controller/RecommentController.java, src/main/java/com/drinkeg/drinkeg/service/commentService/CommentService.java, src/main/java/com/drinkeg/drinkeg/service/commentService/CommentServiceImpl.java, src/main/java/com/drinkeg/drinkeg/service/recommentService/RecommentService.java, src/main/java/com/drinkeg/drinkeg/service/recommentService/RecommentServiceImpl.java
- 모임, 댓글, 대댓글, 모임참여멤버 각각 Refactor해서 전체를 다 받아야 오류 없음
=> #94 Refactor: Comment/Recomment Refactor

src/main/java/com/drinkeg/drinkeg/controller/PartyJoinMemberController.java, src/main/java/com/drinkeg/drinkeg/service/partyJoinMemberService/PartyJoinMemberService.java, src/main/java/com/drinkeg/drinkeg/service/partyJoinMemberService/PartyJoinMemberServiceImpl.java
- PartyJoinMemberController 리팩토링 MemberService 삭제
- PartyJoinMemberService 리팩토링 다른 도메인 Repository 삭제
=> #101 Refactor: PartyJoinMember 리팩토링

src/main/java/com/drinkeg/drinkeg/config/S3Config.java, src/main/java/com/drinkeg/drinkeg/converter/WineLectureCompleteConverter.java, src/main/java/com/drinkeg/drinkeg/converter/WineLectureConverter.java, src/main/java/com/drinkeg/drinkeg/domain/WineNote.java
- WineLecture DTO변환 과정에 author 추가
- S3 aws 경로명 수정
- TastingNote 멤버 변수 ArrayList 선언식 Builder패턴 오류 해결. (final로 선언 변경)
=> #137 Fix: WineLecture, S3, TastingNote Builder 패턴 오류 해결

src/main/java/com/drinkeg/drinkeg/dto/TastingNoteDTO/request/NoteUpdateRequestDTO.java
- NoteUpdateRequestDTO는 Builder사용하지 않는데 Builder.Default 추가했었음
- 삭제 완료
=> #140 Fix: NoteUpdateRequestDTO Builder.Default 삭제

src/main/java/com/drinkeg/drinkeg/controller/WineLectureController.java
- Controller에 Tag 어노테이션 name, description 속성 작성 완료.
- API endpoint에 Operation 어노테이션 summary, description 속성 작성 완료.
=> #126 Refactor: WineLectureController에 Swagger 꾸미기 어노테이션 적용 완료

src/main/java/com/drinkeg/drinkeg/controller/WineClassController.java
- Controller에 Tag 어노테이션 name, description 속성 작성 완료.
- API endpoint에 Operation 어노테이션 summary, description 속성 작성 완료.
=> #128 Refactor: WineClassController에 Swagger 꾸미기 어노테이션 적용 완료

src/main/java/com/drinkeg/drinkeg/apipayLoad/code/status/ErrorStatus.java, src/main/java/com/drinkeg/drinkeg/service/wineClassBookMarkService/WineClassBookMarkServiceImpl.java
- WineClassBookmark와 WineLectureComplete의 중복 엔티티 성성을 ALREADY_EXISTS로 통일.
=> #129 Refactor: WineClassBookMark ErrorStatus 변경

src/main/java/com/drinkeg/drinkeg/jwt/JWTFilter.java
이슈 번호: #159  
작업 내용: jwtFilter 에서 토큰 없을 시 로직 실행 안하도록 처리
=> #159 Fix: nullpointException 처리

src/main/java/com/drinkeg/drinkeg/jwt/CustomLogoutFilter.java, src/main/java/com/drinkeg/drinkeg/jwt/JWTException.java, src/main/java/com/drinkeg/drinkeg/jwt/JWTFilter.java, src/main/java/com/drinkeg/drinkeg/jwt/LoginFilter.java, src/main/java/com/drinkeg/drinkeg/oauth2/CustomSuccessHandler.java, src/main/java/com/drinkeg/drinkeg/service/loginService/AppleLoginService.java, src/main/java/com/drinkeg/drinkeg/service/loginService/TokenService.java
로그아웃시에 access token도 삭제
쿠키에 samsite 설정 추가
=> #205 Refactor: 로그아웃과 쿠키 부분에서 보안 강화

src/main/java/com/drinkeg/drinkeg/controller/WineLectureCompleteController.java, src/main/java/com/drinkeg/drinkeg/repository/wineLectureComplete/WineLectureCompleteRepository.java, src/main/java/com/drinkeg/drinkeg/repository/wineLectureComplete/WineLectureCompleteRepositoryCustom.java, src/main/java/com/drinkeg/drinkeg/repository/wineLectureComplete/WineLectureCompleteRepositoryImpl.java, src/main/java/com/drinkeg/drinkeg/service/WineLectureCompleteService/WineLectureCompleteService.java, src/main/java/com/drinkeg/drinkeg/service/WineLectureCompleteService/WineLectureCompleteServiceImpl.java
- get메소드가 존재하지 않아서 dsl은 인터페이스까지 생성
- 수강완료 삭제 인자를 기존 wineLectureCompleteId에서 wineLectureId와 memberId를 기준으로 변경
- 유저의 완료한 강의 보기 기능 삭제
=> #177 refactor: 와인 강의 완료 리팩토링

src/main/java/com/drinkeg/drinkeg/DrinkegApplication.java, src/main/java/com/drinkeg/drinkeg/domain/comment/domain/Comment.java, src/main/java/com/drinkeg/drinkeg/domain/model/BaseEntity.java, src/main/java/com/drinkeg/drinkeg/domain/model/JpaAuditingConfig.java, src/main/java/com/drinkeg/drinkeg/domain/notice/controller/AdminNoticeController.java, src/main/java/com/drinkeg/drinkeg/domain/notice/controller/NoticeController.java, src/main/java/com/drinkeg/drinkeg/domain/notice/domain/Notice.java, src/main/java/com/drinkeg/drinkeg/domain/notice/domain/NoticeTag.java, src/main/java/com/drinkeg/drinkeg/domain/notice/dto/NoticeRequest.java, src/main/java/com/drinkeg/drinkeg/domain/notice/dto/NoticeResponse.java, src/main/java/com/drinkeg/drinkeg/domain/notice/repository/NoticeRepository.java, src/main/java/com/drinkeg/drinkeg/domain/notice/service/AdminNoticeService.java, src/main/java/com/drinkeg/drinkeg/domain/notice/service/NoticeService.java, src/main/java/com/drinkeg/drinkeg/domain/party/domain/Party.java, src/main/java/com/drinkeg/drinkeg/domain/partyBookmark/domain/PartyBookmark.java, src/main/java/com/drinkeg/drinkeg/domain/partyJoinMember/domain/PartyJoinMember.java, src/main/java/com/drinkeg/drinkeg/domain/recomment/domain/Recomment.java, src/main/java/com/drinkeg/drinkeg/domain/tastingNote/domain/TastingNote.java, src/main/java/com/drinkeg/drinkeg/domain/uuid/domain/Uuid.java, src/main/java/com/drinkeg/drinkeg/domain/wineClassProgress/domain/WineClassProgress.java, src/main/java/com/drinkeg/drinkeg/domain/wineNote/domain/WineNote.java, src/main/java/com/drinkeg/drinkeg/domain/wineWishlist/domain/WineWishlist.java, src/main/java/com/drinkeg/drinkeg/global/apipayLoad/code/status/ErrorStatus.java, src/main/java/com/drinkeg/drinkeg/global/config/SecurityConfig.java, src/test/java/com/drinkeg/drinkeg/domain/notice/controller/AdminNoticeControllerTest.java, src/test/java/com/drinkeg/drinkeg/domain/notice/controller/NoticeControllerTest.java, src/test/java/com/drinkeg/drinkeg/domain/notice/service/AdminNoticeServiceTest.java, src/test/java/com/drinkeg/drinkeg/domain/notice/service/NoticeServiceTest.java
기능구현 완료된 상태로 PR 요청합니다.
validation 테스팅 코드를 아직 작성하지 못하여 추후에 작업할 계획입니다.
Todo
=> #296 Feat: 공지사항 기능 구현 

src/main/java/com/drinkeg/drinkeg/domain/member/converter/MemberConverter.java, src/main/java/com/drinkeg/drinkeg/domain/member/domain/Member.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/MemberResponseDTO.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/loginDTO/commonDTO/PrincipalDetail.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/loginDTO/commonDTO/UserDTO.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/loginDTO/jwtDTO/CustomUserDetails.java, src/main/java/com/drinkeg/drinkeg/domain/member/enums/Provider.java, src/main/java/com/drinkeg/drinkeg/domain/member/enums/Role.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/appleService/AppleLoginService.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/dto/LoginResponseDTO.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/kakao/kakaoService/KakaoLoginService.java, src/main/java/com/drinkeg/drinkeg/domain/member/service/JoinService.java, src/main/java/com/drinkeg/drinkeg/global/apipayLoad/code/status/ErrorStatus.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/JWTFilter.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/LoginFilter.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/TokenService.java
toString 대신 getter 사용
converter 없애기
=> #281 Refactor: getter 사용, converter 사용 안하기

src/main/java/com/drinkeg/drinkeg/domain/member/controller/MemberController.java, src/main/java/com/drinkeg/drinkeg/domain/member/converter/MemberConverter.java, src/main/java/com/drinkeg/drinkeg/domain/member/domain/Member.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/MemberInfoResponse.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/MemberResponseDTO.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/MemberUpdateRequest.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/loginDTO/commonDTO/PrincipalDetail.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/loginDTO/commonDTO/UserDTO.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/loginDTO/jwtDTO/CustomUserDetails.java, src/main/java/com/drinkeg/drinkeg/domain/member/enums/Provider.java, src/main/java/com/drinkeg/drinkeg/domain/member/enums/Role.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/appleService/AppleLoginService.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/dto/LoginResponseDTO.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/kakao/kakaoService/KakaoLoginService.java, src/main/java/com/drinkeg/drinkeg/domain/member/repostitory/MemberRepository.java, src/main/java/com/drinkeg/drinkeg/domain/member/service/JoinService.java, src/main/java/com/drinkeg/drinkeg/domain/member/service/MemberService.java, src/main/java/com/drinkeg/drinkeg/domain/member/service/MemberServiceImpl.java, src/main/java/com/drinkeg/drinkeg/global/apipayLoad/code/status/ErrorStatus.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/JWTFilter.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/LoginFilter.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/TokenService.java
=> # 307 마이페이지 기능 구현 

src/main/java/com/drinkeg/drinkeg/domain/member/controller/MemberController.java, src/main/java/com/drinkeg/drinkeg/domain/member/dto/loginDTO/NameCheckResponse.java, src/main/java/com/drinkeg/drinkeg/domain/member/service/MemberService.java, src/main/java/com/drinkeg/drinkeg/domain/member/service/MemberServiceImpl.java, src/test/java/com/drinkeg/drinkeg/domain/member/repository/MemberRepositoryTest.java, src/test/java/com/drinkeg/drinkeg/domain/member/service/MemberServiceTest.java
=> 닉네임 중복 검사 시에 스웨거에 명시될 수 있도록 수정

src/main/java/com/drinkeg/drinkeg/domain/member/service/MemberServiceImpl.java
- transactional 미설정으로 발생한 오류였음
=> #363 fix: 프로필 사진 업로드 오류 해결

src/main/java/com/drinkeg/drinkeg/domain/member/controller/MemberController.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/appleService/AppleService.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/utils/AppleAuthClient.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/utils/AppleClientSecretGenerator.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/utils/ApplePrivateKeyGenerator.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/utils/AppleProvider.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/controller/OAuth2Controller.java, src/main/java/com/drinkeg/drinkeg/global/apipayLoad/code/status/ErrorStatus.java
=> apple 애플 탈퇴

src/main/java/com/drinkeg/drinkeg/domain/tastingNote/controller/TastingNoteController.java, src/main/java/com/drinkeg/drinkeg/domain/tastingNote/dto/response/AllTastingNoteResponse.java, src/main/java/com/drinkeg/drinkeg/domain/tastingNote/dto/response/TastingNotePreviewResponse.java, src/main/java/com/drinkeg/drinkeg/domain/tastingNote/repository/TastingNoteRepositoryCustom.java, src/main/java/com/drinkeg/drinkeg/domain/tastingNote/repository/TastingNoteRepositoryImpl.java, src/main/java/com/drinkeg/drinkeg/domain/tastingNote/service/TastingNoteService.java, src/main/java/com/drinkeg/drinkeg/domain/tastingNote/service/TastingNoteServiceImpl.java, src/test/java/com/drinkeg/drinkeg/domain/tastingNote/controller/TastingNoteControllerTest.java, src/test/java/com/drinkeg/drinkeg/domain/tastingNote/dto/response/TastingNoteResponseTest.java, src/test/java/com/drinkeg/drinkeg/domain/tastingNote/repository/TastingNoteRepositoryImplTest.java, src/test/java/com/drinkeg/drinkeg/domain/tastingNote/service/TastingNoteServiceImplTest.java
=> #397 Feat: 와인 이름으로 테이스팅 노트 검색 구현

src/main/java/com/drinkeg/drinkeg/global/apipayLoad/code/ReasonDTO.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/CustomAccessDeniedHandler.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/CustomAuthenticationEntryPoint.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/JWTException.java, src/test/java/com/drinkeg/drinkeg/domain/banner/controller/AdminBannerControllerTest.java
{
"isSuccess": false,
"httpStatus": "UNAUTHORIZED",
"code": "ACCESS_TOKEN4001",
"message": "엑세스 토큰이 없습니다."
}
위 형식으로 에러 처리 형식 통일했습니다.
=> #402 Refactor: 예외 처리 형식 통일

src/main/java/com/drinkeg/drinkeg/domain/member/controller/MemberController.java, src/main/java/com/drinkeg/drinkeg/domain/member/service/MemberServiceImpl.java
#410
멤버 이미지 없을 때는 식제로직 안하도록 수정
=> 멤버 탈퇴 로직 수정

.github/ISSUE_TEMPLATE/refactor.md, src/main/java/com/drinkeg/drinkeg/domain/wine/repository/WineRepositoryImpl.java
close #{420}
- 추천 와인 정렬 기준 추가 (별점순)
- Refactor 템플릿 수정
=> #420 추천 와인 정렬 기준 추가 (별점순)

src/main/java/com/drinkeg/drinkeg/domain/wine/service/WineServiceImpl.java
close #{420}
EntityManager clear 추가
=> #420 Refactor: EntityManager clear 추가

src/main/java/com/drinkeg/drinkeg/domain/wine/repository/WineRepositoryImpl.java, src/main/java/com/drinkeg/drinkeg/domain/wine/service/WineServiceImpl.java
close #{420}
- EntityManager clear 삭제
- 가격 0 초과 조건 추가
=> #420 Refactor: entity manager 삭제, 가격 조건 추가

src/main/java/com/drinkeg/drinkeg/domain/wine/repository/WineRepositoryImpl.java
close #{420}
추천 와인 별점순 대신 랜덤으로 변경
=> #420 Refactor: 추천 와인 별점순 대신 랜덤으로 변경

.github/ISSUE_TEMPLATE/refactor.md
=> #428 Fix: refactor.md 수정

src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/appleService/AppleService.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/utils/AppleClientSecretGenerator.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/utils/ApplePrivateKeyGenerator.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/utils/AppleProvider.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/apple/utils/ApplePublicKeyGenerator.java, src/main/java/com/drinkeg/drinkeg/domain/member/login/oauth2/controller/OAuth2Controller.java, src/main/java/com/drinkeg/drinkeg/global/apipayLoad/code/status/ErrorStatus.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/JWTException.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/JWTFilter.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/JWTUtil.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/LoginFilter.java, src/main/java/com/drinkeg/drinkeg/global/security/jwt/TokenService.java
=> #426 Refactor: member 도메인 내에 sout 삭제

src/main/java/com/drinkeg/drinkeg/global/security/jwt/CustomLogoutFilter.java
close #417 
쿠키에서 토큰 추출할때 null 값이 아닌지 여부 체크 추가 
refresh token 만료 여부 관계 없이 로그아웃 가능하도록 수정
=> #417 Refactor: 로그아웃 기능 nullpointException 날만한 부분 리팩토링

src/main/java/com/drinkeg/drinkeg/domain/member/enums/Provider.java
=> #410 Refactor: drinkeg enum 값 변경

src/main/java/com/drinkeg/drinkeg/domain/tastingNote/dto/response/TastingNotePreviewResponse.java, src/main/java/com/drinkeg/drinkeg/domain/tastingNote/dto/response/TastingNoteResponse.java, src/test/java/com/drinkeg/drinkeg/domain/member/controller/MemberControllerTest.java, src/test/java/com/drinkeg/drinkeg/domain/member/service/JoinServiceTest.java, src/test/java/com/drinkeg/drinkeg/domain/member/service/MemberServiceTest.java, src/test/java/com/drinkeg/drinkeg/domain/tastingNote/controller/TastingNoteControllerTest.java, src/test/java/com/drinkeg/drinkeg/domain/tastingNote/dto/response/TastingNoteResponseTest.java, src/test/java/com/drinkeg/drinkeg/domain/tastingNote/service/TastingNoteServiceImplTest.java
close #447
테이스팅 노트 조회 시 작성날짜  (createdAt) 추가
=> #447 : 테이스팅 노트 조회 시 작성 날짜 추가

src/main/java/com/drinkeg/drinkeg/domain/wine/controller/AdminWineController.java, src/main/java/com/drinkeg/drinkeg/domain/wine/dto/response/AdminWineDetailResponse.java, src/main/java/com/drinkeg/drinkeg/domain/wine/dto/response/AdminWineResponse.java, src/main/java/com/drinkeg/drinkeg/domain/wine/service/AdminWineService.java, src/main/java/com/drinkeg/drinkeg/domain/wine/service/AdminWineServiceImpl.java, src/test/java/com/drinkeg/drinkeg/domain/wine/controller/AdminWineControllerTest.java, src/test/java/com/drinkeg/drinkeg/domain/wine/dto/response/AdminWineResponseTest.java, src/test/java/com/drinkeg/drinkeg/domain/wine/service/AdminWineServiceImplMockTest.java, src/test/java/com/drinkeg/drinkeg/domain/wine/service/AdminWineServiceImplTest.java
close #446
관리자용 와인 단건 조회 구현 및 테스트 코드 작성
=> #446 관리자용 와인 단건 조회 

src/main/java/com/drinkeg/drinkeg/domain/wine/controller/AdminWineController.java, src/main/java/com/drinkeg/drinkeg/domain/wine/domain/Wine.java, src/main/java/com/drinkeg/drinkeg/domain/wine/dto/response/AdminWineDetailResponse.java, src/main/java/com/drinkeg/drinkeg/domain/wine/dto/response/AdminWinePreviewResponse.java, src/main/java/com/drinkeg/drinkeg/domain/wine/dto/response/AdminWineResponse.java, src/main/java/com/drinkeg/drinkeg/domain/wine/repository/WineRepositoryCustom.java, src/main/java/com/drinkeg/drinkeg/domain/wine/repository/WineRepositoryImpl.java, src/main/java/com/drinkeg/drinkeg/domain/wine/service/AdminWineService.java, src/main/java/com/drinkeg/drinkeg/domain/wine/service/AdminWineServiceImpl.java, src/test/java/com/drinkeg/drinkeg/domain/member/controller/MemberControllerTest.java, src/test/java/com/drinkeg/drinkeg/domain/member/service/JoinServiceTest.java, src/test/java/com/drinkeg/drinkeg/domain/member/service/MemberServiceTest.java, src/test/java/com/drinkeg/drinkeg/domain/wine/controller/AdminWineControllerTest.java, src/test/java/com/drinkeg/drinkeg/domain/wine/dto/response/AdminWineResponseTest.java, src/test/java/com/drinkeg/drinkeg/domain/wine/repository/WineRepositoryImplTest.java, src/test/java/com/drinkeg/drinkeg/domain/wine/service/AdminWineSearchServiceImplTest.java, src/test/java/com/drinkeg/drinkeg/domain/wine/service/AdminWineServiceImplMockTest.java, src/test/java/com/drinkeg/drinkeg/domain/wine/service/AdminWineServiceImplTest.java
close #444
- 관리자용 와인 검색 구현
- 테스트 코드 작성 완료
=> #444 : 관리자용 와인 검색 구현

src/main/java/com/drinkeg/drinkeg/global/security/jwt/TokenService.java
=> refactor : 쿠키 Samesite 설정 none으로 변경 (#343)

.github/workflows/drinkig-cd.yml, .github/workflows/drinkig-ci.yml
=> CI/CD 워크플로우 변경사항 반영

.github/workflows/drinkig-cd.yml, .github/workflows/drinkig-ci.yml
=> #455 refactor: 불필요한 주석 제거

.github/workflows/drinkig-dev-cd.yml, .github/workflows/drinkig-prod-cd.yml
close #463
- 기존 docker-compose 로 돼있던 명령어를 docker compose로 수정
=> chore: docker compose 명령어 수정 (#463)

.github/workflows/drinkig-dev-cd.yml, .github/workflows/drinkig-prod-cd.yml
close #463 
- docker-compose 명령어에 -p 프로젝트 지정 명령어 추가
=> chore: docker-compose 명령어 수정

.github/workflows/drinkig-dev-cd.yml, .github/workflows/drinkig-prod-cd.yml
close #463
- docker-compose up 순서 오류 수정
=> chore: docker-compose up 순서 오류 수정

.github/workflows/drinkig-cd.yml, .github/workflows/drinkig-ci.yml
=> chore: docker compose 명령어 수정
